---
# Source: openldap/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: openldap
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: openldap
    heritage: Helm
type: Opaque
data:
  LDAP_ADMIN_PASSWORD: "Z3FFYnVrSGVEYTRVcE02MFAyNGFOTHlQZ2dqamlkYjY="
  LDAP_CONFIG_PASSWORD: "dWt4cDZ5Q2p6WkJiYlZuOUJFNGs1MjJmR0tkaXNra0w="
---
# Source: openldap/templates/configmap-env.yaml
#
# A ConfigMap spec for openldap slapd that map directly to env variables in the Pod.
# List of environment variables supported is from the docker image:
# https://github.com/osixia/docker-openldap#beginner-guide
# Note that passwords are defined as secrets
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-env
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: openldap
    heritage: Helm
data:
  LDAP_BACKEND: hdb
  LDAP_DOMAIN: kejialiu.net
  LDAP_ORGANISATION: Kejia Liu
  LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
  LDAP_TLS: "true"
  LDAP_TLS_ENFORCE: "false"
  LDAP_TLS_VERIFY_CLIENT: never
---
# Source: openldap/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openldap
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: openldap
    heritage: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
  storageClassName: "openldap-sc"
---
# Source: openldap/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: openldap
    heritage: Helm
spec:
  clusterIP: ""
  ports:
    - name: ldap-port
      protocol: TCP
      port: 389
      targetPort: ldap-port
    - name: ssl-ldap-port
      protocol: TCP
      port: 636
      targetPort: ssl-ldap-port
  selector:
    app: openldap
    release: openldap
  type: ClusterIP
---
# Source: openldap/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  openldap
  labels:
    app: openldap
    chart: openldap-1.2.3
    release: openldap
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
      release: openldap
  template:
    metadata:
      annotations:
        checksum/configmap-env: ac0b64f1c5d2872ae33918d89b4dd6487a9fd3a63c13ae5632463049ddb2577f
      labels:
        app: openldap
        release: openldap
    spec:
      initContainers:
      - name: openldap-init-tls
        image: busybox
        command: ['sh', '-c', 'cp /tls/* /certs']
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: tls
            mountPath: /tls
          - name: certs
            mountPath: /certs
        resources:
          {}
      containers:
        - name: openldap
          image: "osixia/openldap:1.2.4"
          imagePullPolicy: IfNotPresent
          ports:
            - name: ldap-port
              containerPort: 389
            - name: ssl-ldap-port
              containerPort: 636
          envFrom:
            - configMapRef:
                name: openldap-env
            - secretRef:
                name: openldap
          volumeMounts:
            - name: data
              mountPath: /var/lib/ldap
              subPath: data
            - name: data
              mountPath: /etc/ldap/slapd.d
              subPath: config-data
            - name: certs
              mountPath: /container/service/slapd/assets/certs
          env:
            - name: LDAP_TLS_CRT_FILENAME
              value: tls.crt
            - name: LDAP_TLS_KEY_FILENAME
              value: tls.key
          livenessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: ldap-port
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 10
          resources:
            {}
      volumes:
        - name: tls
          secret:
            secretName: ldap-kejialiu-net-certs
        - name: certs
          emptyDir:
            medium: Memory
        - name: data
          persistentVolumeClaim:
            claimName: openldap
---
# Source: openldap/templates/configmap-customldif.yaml
#
# A ConfigMap spec for openldap slapd that map directly to files under
# /container/service/slapd/assets/config/bootstrap/ldif/custom
#
